# Generated by Django 4.1.1 on 2022-11-03 23:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Dueño', 'Dueño'), ('Comisionista', 'Comisionista')], default='Comisionista', max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDO', 'Vendido'), ('ALQUILADO', 'Alquilado'), ('RESERVADO', 'Reservado')], default='DISPONIBLE', max_length=10)),
                ('localidad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CASA1', 'Casa en Venta'), ('CASA2', 'Casa en Alquiler'), ('TERRENO1', 'Terreno en Venta'), ('TERRENO2', 'Terreno en Alquiler'), ('CAMPO_GANADERO1', 'Campo Ganadero en Venta'), ('CAMPO_GANADERO2', 'Campo Ganadero en Alquiler'), ('CAMPO_MIXTO1', 'Campo Mixto en Venta'), ('CAMPO_MIXTO2', 'Campo Mixto en Alquiler'), ('CAMPO_AGRICOLA1', 'Campo Agrícola en Venta'), ('CAMPO_AGRICOLA2', 'Campo Agrícola en Alquiler'), ('MAQUINARIA1', 'Maquinaria en Venta'), ('MAQUINARIA2', 'Maquinaria en Alquiler')], max_length=50)),
                ('moneda', models.CharField(choices=[('Pesos', 'Pesos'), ('Dolares', 'Dolares')], default='Dolares', max_length=7)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ubicacion', models.TextField(blank=True, null=True, verbose_name='Enlace de Google Maps')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ManyToManyField(blank=True, to='ventas.imagen')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_vendedor', to='ventas.vendedor')),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
